spring.application.name=wrapper

spring.datasource.url=jdbc:postgresql://localhost:5432/shortlink
spring.datasource.username=postgres
spring.datasource.password=root@123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Sakibsheikh2950@gmail.com
spring.mail.password=upuz rjgl dotx jiaq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.org.springframework.security=DEBUG





